### ISSUE TITLE
Create file: concepts.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/soep-base#8]
### Task
- Please create a file according to the spec in the branch `data-unification`.
- Commit with `[close #8] Create file: concepts.csv`

### Spec
filename = `concepts.csv`
location = `metadata/`
headers = `study, name, label, label_de, description, description_de`

### Desired content
- all concepts that are referenced in `metadata/logical_variables.csv`
- study: `soep-base`

**Comment by mpahl** [comment]
Label are still missing!

**Comment by afuetterer** [comment]
Needs `topic` column as well.

**Comment by afuetterer** [comment]
Done. File passed validation.
